version: '3.8'
services:
  mc:
    image: itzg/minecraft-server:latest
    environment:
      EULA: 'TRUE'
      ENABLE_QUERY: 'true'
    ports:
    - "25565:25565"
    - "25565:25565/udp"
    volumes:
      - mcdata:/data

volumes:
  mcdata: